testing actions

diff --git a/.github/workflows/ci-pipeline.yaml b/.github/workflows/ci-pipeline.yaml
--- a/.github/workflows/ci-pipeline.yaml
+++ b/.github/workflows/ci-pipeline.yaml
@@ -32,6 +32,8 @@ jobs:
 
   trigger-banner-dag:
     runs-on: ubuntu-latest
+    outputs:
+      dag_completed: ${{ steps.wait-for-dag.outputs.dag_completed }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -42,164 +44,193 @@ jobs:
         with:
           files: data_pipeline/**
           files_ignore: data_pipeline/dags/tests/**
-      
-      - name: Skip DAG Trigger
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: |
-            echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
-            exit 0
 
       - name: Skip DAG Trigger
         if: steps.changed-files-specific.outputs.any_changed != 'true'
         run: |
             echo "No changes in data_pipeline detected. Skipping DAG trigger."
             exit 0
-
-      - name: Setup Auth
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
-          project_id: coursecompass
-
-      - name: Trigger DAG
+      - name: testing triggers
+        id: wait-for-dag
         run: |
-          gcloud composer environments run data-pipeline-v3 \
-            --location us-east1 \
-            dags trigger -- banner_dag_pipeline
-            echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
+          echo "dag_completed: true" >> $GITHUB_OUTPUT
 
-      - name: Wait for DAG Completion
-        run: |
-          ATTEMPTS=0
-          MAX_ATTEMPTS=20
-          SLEEP_TIME=60  # 60 seconds between checks
+      # - name: Setup Auth
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   uses: google-github-actions/auth@v1
+      #   with:
+      #     credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+      #     project_id: coursecompass
 
-          while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
-            STATUS=$(gcloud composer environments run data-pipeline-v3 \
-              --location us-east1 \
-              dags list-runs --filter="dag_id=banner_dag_pipeline" \
-              --format="value(state)" | head -n 1)
+      # - name: Trigger DAG
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: |
+      #     gcloud composer environments run data-pipeline-v3 \
+      #       --location us-east1 \
+      #       dags trigger -- banner_dag_pipeline
+      #       echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
 
-            if [[ "$STATUS" == "success" ]]; then
-              echo "DAG completed successfully."
-              exit 0
-            elif [[ "$STATUS" == "failed" ]]; then
-              echo "DAG failed."
-              exit 1
-            else
-              echo "DAG still running... Checking again in $SLEEP_TIME seconds."
-              ((ATTEMPTS++))
-              sleep $SLEEP_TIME
-            fi
-          done
+      # - name: Wait for DAG Completion
+      #   id: wait-for-dag
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: |
+      #     ATTEMPTS=0
+      #     MAX_ATTEMPTS=20
+      #     SLEEP_TIME=60  # 60 seconds between checks
 
-          echo "DAG did not complete within the expected time."
-          exit 1
+      #     while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
+      #       STATUS=$(gcloud composer environments run data-pipeline-v3 \
+      #         --location us-east1 \
+      #         dags list-runs --filter="dag_id=banner_dag_pipeline" \
+      #         --format="value(state)" | head -n 1)
+
+      #       if [[ "$STATUS" == "success" ]]; then
+      #         echo "DAG completed successfully."
+      #         echo "dag_completed: true" >> $GITHUB_OUTPUT
+      #         exit 0
+      #       elif [[ "$STATUS" == "failed" ]]; then
+      #         echo "DAG failed."
+      #         echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #         exit 1
+      #       else
+      #         echo "DAG still running... Checking again in $SLEEP_TIME seconds."
+      #         ((ATTEMPTS++))
+      #         sleep $SLEEP_TIME
+      #       fi
+      #     done
+
+      #     echo "DAG did not complete within the expected time."
+      #     echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #     exit 1
 
   trigger-trace-dag:
     runs-on: ubuntu-latest
     needs: trigger-banner-dag
+    if: ${{ needs.trigger-banner-dag.outputs.dag_completed == 'true' }}
+    outputs:
+      dag_completed: ${{ steps.wait-for-dag.outputs.dag_completed }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Setup Auth
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
-          project_id: coursecompass
-
-      - name: Trigger DAG
+      - name: Check if files have been changed in model_training
+        id: wait-for-dag
         run: |
-          echo "DAG triggered. Monitoring for completion..."
+          echo "dag_completed: true" >> $GITHUB_OUTPUT
 
-      - name: Trigger PDF Processing DAG
-        id: trigger_dag
-        run: |
-          gcloud composer environments run data-pipeline-v3 \
-            --location us-east1 \
-            dags trigger -- pdf_processing_pipeline
-          echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
+      # - name: Setup Auth
+      #   uses: google-github-actions/auth@v1
+      #   with:
+      #     credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+      #     project_id: coursecompass
 
-      - name: Wait for PDF Processing DAG Completion
-        id: wait_for_dag
-        run: |
-          ATTEMPTS=0
-          MAX_ATTEMPTS=20
-          SLEEP_TIME=60  # 60 seconds between checks
+      # - name: Trigger DAG
+      #   run: |
+      #     echo "DAG triggered. Monitoring for completion..."
 
-          while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
-            STATUS=$(gcloud composer environments run data-pipeline-v3 \
-              --location us-east1 \
-              dags list-runs --filter="dag_id=pdf_processing_pipeline" \
-              --format="value(state)" | head -n 1)
+      # - name: Trigger PDF Processing DAG
+      #   id: trigger_dag
+      #   run: |
+      #     gcloud composer environments run data-pipeline-v3 \
+      #       --location us-east1 \
+      #       dags trigger -- pdf_processing_pipeline
+      #     echo "Changes in data_pipeline detected. DAG triggered. Monitoring for completion..."
 
-            if [[ "$STATUS" == "success" ]]; then
-              echo "DAG completed successfully."
-              exit 0
-            elif [[ "$STATUS" == "failed" ]]; then
-              echo "DAG failed."
-              exit 1
-            else
-              echo "DAG still running... Checking again in $SLEEP_TIME seconds."
-              ((ATTEMPTS++))
-              sleep $SLEEP_TIME
-            fi
-          done
+      # - name: Wait for PDF Processing DAG Completion
+      #   id: wait-for-dag
+      #   run: |
+      #     ATTEMPTS=0
+      #     MAX_ATTEMPTS=20
+      #     SLEEP_TIME=60  # 60 seconds between checks
 
-          echo "DAG did not complete within the expected time."
-          exit 1
+      #     while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
+      #       STATUS=$(gcloud composer environments run data-pipeline-v3 \
+      #         --location us-east1 \
+      #         dags list-runs --filter="dag_id=pdf_processing_pipeline" \
+      #         --format="value(state)" | head -n 1)
+
+      #       if [[ "$STATUS" == "success" ]]; then
+      #         echo "DAG completed successfully."
+      #         echo "dag_completed: true" >> $GITHUB_OUTPUT
+      #         exit 0
+      #       elif [[ "$STATUS" == "failed" ]]; then
+      #         echo "DAG failed."
+      #         echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #         exit 1
+      #       else
+      #         echo "DAG still running... Checking again in $SLEEP_TIME seconds."
+      #         ((ATTEMPTS++))
+      #         sleep $SLEEP_TIME
+      #       fi
+      #     done
+
+      #     echo "DAG did not complete within the expected time."
+      #     echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #     exit 1
 
   trigger-train-data-dag:
     runs-on: ubuntu-latest
     needs: trigger-trace-dag
+    if: ${{ needs.trigger-trace-dag.outputs.dag_completed == 'true' }}
+    outputs:
+      dag_completed: ${{ steps.wait-for-dag.outputs.dag_completed }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Setup Auth
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
-          project_id: coursecompass
-
-      - name: Trigger DAG
+      - name: Check if files have been changed in model_training
+        id: wait-for-dag
         run: |
-          gcloud composer environments run data-pipeline-v3 \
-            --location us-east1 \
-            dags trigger -- train_data_dag
-            echo "DAG triggered. Monitoring for completion..."
+          echo "dag_completed: true" >> $GITHUB_OUTPUT
 
-      - name: Wait for DAG Completion
-        run: |
-          ATTEMPTS=0
-          MAX_ATTEMPTS=20
-          SLEEP_TIME=60  # 60 seconds between checks
+      # - name: Setup Auth
+      #   uses: google-github-actions/auth@v1
+      #   with:
+      #     credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+      #     project_id: coursecompass
 
-          while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
-            STATUS=$(gcloud composer environments run data-pipeline-v3 \
-              --location us-east1 \
-              dags list-runs --filter="dag_id=train_data_dag" \
-              --format="value(state)" | head -n 1)
+      # - name: Trigger DAG
+      #   run: |
+      #     gcloud composer environments run data-pipeline-v3 \
+      #       --location us-east1 \
+      #       dags trigger -- train_data_dag
+      #       echo "DAG triggered. Monitoring for completion..."
 
-            if [[ "$STATUS" == "success" ]]; then
-              echo "DAG completed successfully."
-              exit 0
-            elif [[ "$STATUS" == "failed" ]]; then
-              echo "DAG failed."
-              exit 1
-            else
-              echo "DAG still running... Checking again in $SLEEP_TIME seconds."
-              ((ATTEMPTS++))
-              sleep $SLEEP_TIME
-            fi
-          done
+      # - name: Wait for DAG Completion
+      #   id: wait-for-dag
+      #   run: |
+      #     ATTEMPTS=0
+      #     MAX_ATTEMPTS=20
+      #     SLEEP_TIME=60  # 60 seconds between checks
 
-          echo "DAG did not complete within the expected time."
-          exit 1
+      #     while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
+      #       STATUS=$(gcloud composer environments run data-pipeline-v3 \
+      #         --location us-east1 \
+      #         dags list-runs --filter="dag_id=train_data_dag" \
+      #         --format="value(state)" | head -n 1)
+
+      #       if [[ "$STATUS" == "success" ]]; then
+      #         echo "DAG completed successfully."
+      #         echo "dag_completed: true" >> $GITHUB_OUTPUT
+      #         exit 0
+      #       elif [[ "$STATUS" == "failed" ]]; then
+      #         echo "DAG failed."
+      #         echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #         exit 1
+      #       else
+      #         echo "DAG still running... Checking again in $SLEEP_TIME seconds."
+      #         ((ATTEMPTS++))
+      #         sleep $SLEEP_TIME
+      #       fi
+      #     done
+
+      #     echo "DAG did not complete within the expected time."
+      #     echo "dag_completed: false" >> $GITHUB_OUTPUT
+      #     exit 1
   
   trigger-model-training-dag:
     runs-on: ubuntu-latest
+    needs: trigger-train-data-dag
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -208,52 +239,61 @@ jobs:
         id: changed-files-specific
         uses: tj-actions/changed-files@v45
         with:
-          files: modeel_training/**
+          files: model_training/**
           files_ignore: model_training/dags/tests/**
 
-      - name: Skip DAG Trigger
+      - name: Skip DAG Trigger Check
         if: steps.changed-files-specific.outputs.any_changed != 'true'
         run: |
             echo "No changes in model_training detected. Skipping DAG trigger."
             exit 0
-
-      - name: Setup Auth
-        uses: google-github-actions/auth@v1
-        with:
-          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
-          project_id: coursecompass
-
-      - name: Trigger DAG
+      - name: Skip DAG Trigger Check
+        if: steps.changed-files-specific.outputs.any_changed == 'true' || needs.trigger-train-data-dag.outputs.dag_completed == 'true'
         run: |
-          gcloud composer environments run data-pipeline-v3 \
-            --location us-east1 \
-            dags trigger -- train_model_trigger_dag
-            echo "Changes in model_training detected. DAG triggered. Monitoring for completion..."
+            echo "Changes in model_training detected. Triggering DAG."
+            exit 0
 
-      - name: Wait for DAG Completion
-        run: |
-          ATTEMPTS=0
-          MAX_ATTEMPTS=40
-          SLEEP_TIME=60  # 60 seconds between checks
+      # - name: Setup Auth
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' || needs.trigger-train-data-dag.outputs.dag_completed == 'true'
+      #   uses: google-github-actions/auth@v1
+      #   with:
+      #     credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
+      #     project_id: coursecompass
 
-          while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
-            STATUS=$(gcloud composer environments run data-pipeline-v3 \
-              --location us-east1 \
-              dags list-runs --filter="dag_id=train_model_trigger_dag" \
-              --format="value(state)" | head -n 1)
+      # - name: Trigger DAG
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' || needs.trigger-train-data-dag.outputs.dag_completed == 'true'
+      #   run: |
+      #     gcloud composer environments run data-pipeline-v3 \
+      #       --location us-east1 \
+      #       dags trigger -- train_model_trigger_dag
+      #       echo "Changes in model_training detected. DAG triggered. Monitoring for completion..."
 
-            if [[ "$STATUS" == "success" ]]; then
-              echo "DAG completed successfully."
-              exit 0
-            elif [[ "$STATUS" == "failed" ]]; then
-              echo "DAG failed."
-              exit 1
-            else
-              echo "DAG still running... Checking again in $SLEEP_TIME seconds."
-              ((ATTEMPTS++))
-              sleep $SLEEP_TIME
-            fi
-          done
+      # - name: Wait for DAG Completion
+      #   id: wait-for-dag
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true' || needs.trigger-train-data-dag.outputs.dag_completed == 'true'
+      #   run: |
+      #     ATTEMPTS=0
+      #     MAX_ATTEMPTS=40
+      #     SLEEP_TIME=60  # 60 seconds between checks
 
-          echo "DAG did not complete within the expected time."
-          exit 1
+      #     while [[ $ATTEMPTS -lt $MAX_ATTEMPTS ]]; do
+      #       STATUS=$(gcloud composer environments run data-pipeline-v3 \
+      #         --location us-east1 \
+      #         dags list-runs --filter="dag_id=train_model_trigger_dag" \
+      #         --format="value(state)" | head -n 1)
+
+      #       if [[ "$STATUS" == "success" ]]; then
+      #         echo "DAG completed successfully."
+      #         exit 0
+      #       elif [[ "$STATUS" == "failed" ]]; then
+      #         echo "DAG failed."
+      #         exit 1
+      #       else
+      #         echo "DAG still running... Checking again in $SLEEP_TIME seconds."
+      #         ((ATTEMPTS++))
+      #         sleep $SLEEP_TIME
+      #       fi
+      #     done
+
+      #     echo "DAG did not complete within the expected time."
+      #     exit 1
